// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp4N399eMOhvzOFurs749WsmcOQEY8Ha4',
    appId: '1:835465547069:web:442a45727f6bb632210954',
    messagingSenderId: '835465547069',
    projectId: 'snakegame-ad5ed',
    authDomain: 'snakegame-ad5ed.firebaseapp.com',
    storageBucket: 'snakegame-ad5ed.appspot.com',
    measurementId: 'G-00C5514RS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAws0sVVAIU3Sc_jYiEXPMsa31ot4604h8',
    appId: '1:835465547069:android:bffb8727e0c3901f210954',
    messagingSenderId: '835465547069',
    projectId: 'snakegame-ad5ed',
    storageBucket: 'snakegame-ad5ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0AYY8cKOPYhPsnoWswgbnkHik0YbfVek',
    appId: '1:835465547069:ios:76064cb8f0b3f593210954',
    messagingSenderId: '835465547069',
    projectId: 'snakegame-ad5ed',
    storageBucket: 'snakegame-ad5ed.appspot.com',
    iosClientId: '835465547069-pguc8m9p913psbr0vurhug32ufet8ovd.apps.googleusercontent.com',
    iosBundleId: 'com.example.snakegame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0AYY8cKOPYhPsnoWswgbnkHik0YbfVek',
    appId: '1:835465547069:ios:df6ded0a4c03242e210954',
    messagingSenderId: '835465547069',
    projectId: 'snakegame-ad5ed',
    storageBucket: 'snakegame-ad5ed.appspot.com',
    iosClientId: '835465547069-sqo1981vimvmein9pqjqd2e5b4uak350.apps.googleusercontent.com',
    iosBundleId: 'com.example.snakegame.RunnerTests',
  );
}
