// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS0b_rgLxpAzbU8z18LYhxY4TNxXp3v2k',
    appId: '1:915493975600:web:876e9735c393915b341ff5',
    messagingSenderId: '915493975600',
    projectId: 'login-akd',
    authDomain: 'login-akd.firebaseapp.com',
    storageBucket: 'login-akd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Gd_sSb13SPzu00EuMFku8adm1cVO-GU',
    appId: '1:915493975600:android:2531ec0a596abe95341ff5',
    messagingSenderId: '915493975600',
    projectId: 'login-akd',
    storageBucket: 'login-akd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa73mgXjdYfbvI0NiaPUgrQwttcheNi4U',
    appId: '1:915493975600:ios:380ada63fb4bfab2341ff5',
    messagingSenderId: '915493975600',
    projectId: 'login-akd',
    storageBucket: 'login-akd.appspot.com',
    iosClientId: '915493975600-uktas007dllh1o8fu2ko75q1u3kfqi36.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFireBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa73mgXjdYfbvI0NiaPUgrQwttcheNi4U',
    appId: '1:915493975600:ios:2c54fb86d5916d31341ff5',
    messagingSenderId: '915493975600',
    projectId: 'login-akd',
    storageBucket: 'login-akd.appspot.com',
    iosClientId: '915493975600-tsgceg6lku4jol6bar23vehqbthif20q.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFireBase.RunnerTests',
  );
}
